---
- hosts: all
  tasks:
   - name: debug loops
     vars:
        yn_domain: pre-mb.yinuojr.cn
        yn_log: pre_mb
        yn_cer: server.cer
        yn_key: server.key
        yn_webdir: /bubidata/server/nginx/html/platform_yinuojr
        yn_tag: mibu
        yn_gateway: gateway.yinuojr.local

     template: src=temp.j2   dest=/home/wuwenyu/{{ yn_log }}.conf
